name: Polaris CI

on: [push, pull_request, workflow_dispatch]

jobs:

  Polaris-ST-Pipeline:
    runs-on: ubuntu-latest
    container: vitormcruz/pharo:11
    steps:
      - uses: actions/checkout@v4

      - name: Pharo Version
        run: pharo /opt/pharo/Pharo.image printVersion;
      
      - name: Build
        run: pharo /opt/pharo/Pharo.image st --save --quit loadForPipeline.st;

      - name: Run Tests
        run: pharo /opt/pharo/Pharo.image test --fail-on-failure --fail-on-error Polaris-Tests --save;

      - name: Save Error Logs/Files
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          path: |
               /opt/pharo/std*
               /opt/pharo/*.log
               fueled_out_errors/*
          if-no-files-found: ignore
          retention-days: 1
